Upgrading to java 11 WIP
TAMULib/CAP pull request #174
Opened 2022-04-08 19:25 UTC by rladdusaw

Resolves #153

2022-05-17 20:38 UTC, kaladay requested changes
In the pom.xml, code like:
```
              <!-- NPM Install -->
              <execution>
                <id>exec-npm-install</id>
                <phase>generate-sources</phase>
...
```

According to eclipse:
```
Plugin execution not covered by lifecycle configuration: org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (execution: exec-npm-install, phase: generate-sources)
```
For lines: 529, 547, 562, 578.
I do not know if this is true/false so I figured I would mention it.

I get the following:
```
ServletRegistrationBean is a raw type. References to generic type ServletRegistrationBean<T> should be parameterized
```
for:
```
    @Bean
    public ServletRegistrationBean h2servletRegistration() {
        ServletRegistrationBean registrationBean = new ServletRegistrationBean(new WebServlet());
```

I replaced this with:
```
    @Bean
    public ServletRegistrationBean<WebServlet> h2servletRegistration() {
        ServletRegistrationBean<WebServlet> registrationBean = new ServletRegistrationBean<WebServlet>(new WebServlet());
```
If this is a correct thing to do, then I suggest such a change.


The 
```
private final Logger logger = LoggerFactory.getLogger(this.getClass());
```
in `MapService.java` is not used.
I suggest considering removing it.

2022-05-17 20:38 UTC, kaladay commented on pom.xml
> -      <version>1.4.01</version><!--$NO-MVN-MAN-VER$ -->
The original version (1.4.01) is actually correct and more recent than 2.0.2.
We need to add a comment to document this confusion.

2022-05-17 20:38 UTC, kaladay commented on pom.xml
> +      <version>0.13.4</version>
An exclusion for jackson-databind is necessary due to a vulnerability in it:
- [CVE-2020-36518](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-36518)

We should explicitly include a version like 2.13.3.

2022-05-17 20:38 UTC, kaladay commented on pom.xml
> +          <groupId>org.junit.vintage</groupId>
Vintage no longer needs to be excluded.
The latest spring boot starter test does not include it.
Please remove the exclusion.

2022-05-17 20:38 UTC, kaladay commented on src/main/java/edu/tamu/cap/config/AppH2ConsoleConfig.java
> +        ServletRegistrationBean<WebServlet> registrationBean = new ServletRegistrationBean<WebServlet>(new WebServlet());
Should be able to change `<WebServlet>` to `<>` on the right side of the equal.

2022-05-17 20:38 UTC, kaladay commented on src/main/resources/application.yml
> +    allow-circular-references: true
There needs to be an issue created for the `    allow-circular-references: true`.

2022-05-17 20:38 UTC, kaladay commented on pom.xml
> +        <version>3.2.0</version>
This version is already in the managed version and should be removed.

2022-05-17 20:38 UTC, kaladay commented on src/test/java/edu/tamu/cap/auth/service/AppUserCredentialsServiceTest.java
> +        MockitoAnnotations.openMocks(this);
We shouldn't be using either of these:
```
        MockitoAnnotations.initMocks(this);
        MockitoAnnotations.openMocks(this);
```

instead, prefix the class with this annotation:
```
@ExtendWith(MockitoExtension.class)
```

Also, the `@SpringBootTest` annotation already includes `@ExtendWith(SpringExtension.class)`, so please remove this from line ~31.

2022-05-17 20:38 UTC, kaladay commented on src/test/java/edu/tamu/cap/controller/SchemaControllerTest.java
> +@ExtendWith(SpringExtension.class)
`@SpringBootTest` already includes this, please remove `ExtendWith(SpringExtension.class)`.

2022-05-17 20:38 UTC, kaladay commented on src/test/java/edu/tamu/cap/controller/UserControllerTest.java
> +@ExtendWith(SpringExtension.class)
`@SpringBootTest` already includes this, please remove `ExtendWith(SpringExtension.class)`.

2022-05-17 20:38 UTC, kaladay commented on src/test/java/edu/tamu/cap/controller/VerifyRepositoryViewSettingsControllerTest.java
> +@ExtendWith(SpringExtension.class)
`@SpringBootTest` already includes this, please remove `ExtendWith(SpringExtension.class)`.

2022-05-17 20:38 UTC, kaladay commented on src/test/java/edu/tamu/cap/service/FedoraServiceTest.java
>  @ExtendWith(SpringExtension.class)
`@SpringBootTest` already includes this, please remove `ExtendWith(SpringExtension.class)`.

2022-05-17 20:38 UTC, kaladay commented on src/test/java/edu/tamu/cap/service/FedoraServiceTest.java
> +        MockitoAnnotations.openMocks(this);
Remove this and instead add:
```
ExtendWith(MockitoExtension.class)
```

2022-05-17 20:38 UTC, kaladay commented on src/test/resources/application.yml
> +  file.name: logs/cap.log
I started a practice of adding `-test` to the test log file.
I request changing this to:
```
file.name: logs/cap-test.log
```

2022-05-17 20:41 UTC, rladdusaw commented on Dockerfile
> +RUN npm install -g grunt-cli
It is necessary, you can't install a global package without root.

2022-05-17 20:42 UTC, kaladay commented
I also suggest adding a logback file to further simplify the output when running tests.
Here is an example I copied from iriif:
`src/test/resources/logback-test.xml`:
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <include resource="org/springframework/boot/logging/logback/base.xml" />
  <logger name="com.zaxxer" level="ERROR"/>
  <logger name="org.hibernate" level="OFF"/>
  <logger name="org.springframework" level="ERROR"/>
  <logger name="edu.tamu.iiif" level="WARN"/>
  <property name="root.level.console" value="OFF"/>
</configuration>

```

2022-05-19 15:51 UTC, kaladay commented on pom.xml
> +  <packaging>${packaging}</packaging>
I request doing the following to be consistent.
Change packaging in this manner:
```
  <properties>
    <maven.packaging>war</maven.packaging>
  </properties>

  <packaging>${maven.packaging}</packaging>

  <profiles>
    <profile>
      <id>war</id>
      <properties>
        <maven.packaging>war</maven.packaging>
      </properties>
    </profile>
    <profile>
      <id>jar</id>
      <properties>
        <maven.packaging>jar</maven.packaging>
      </properties>
    </profile>
  </profiles>
  ```

2022-05-19 15:55 UTC, kaladay commented on pom.xml
> +  <packaging>${packaging}</packaging>
You can also do this:
```
  <properties>
    <maven.packaging>${packaging}</maven.packaging>
  </properties>
  ```
  Preserving the behavior of using `${packagin}` by default.

2022-05-19 16:10 UTC, kaladay commented on pom.xml
> +        <version>3.2.2</version>
See if you can use version `3.0.0` as it doesn't bring in dependencies with CVEs at this time.

2022-05-19 18:51 UTC, kaladay commented on pom.xml
> +            <version>2.0.3.RELEASE</version>
I think we should use version `<version>2.0.6.RELEASE</version>`.
None of its dependencies currently have a CVE as `2.0.3.RELEASE` does.

2022-05-19 18:51 UTC, kaladay commented on src/main/resources/application.yml
> +      database-platform: org.hibernate.dialect.H2Dialect
This is incorrect.

The `spring.datasource.jpa.dabase-platform` needs to be changed to `spring.jpa.database-platform`.

There is a `jpa` around line 46 below that this should be moved to.

see: [spring.jpa.database-platform](https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.data.spring.jpa.database-platform)

2022-05-20 13:31 UTC, kaladay commented on src/main/resources/application.yml
> +    allow-circular-references: true
I went ahead and created the issue here: #178 .

2022-06-20 19:16 UTC, kaladay commented on pom.xml
> +      <version>0.13.4</version>
This can be solved by switching to the new Spring-boot 2.7.0 (or greater).

2022-06-21 00:17 UTC, wwelling commented on src/test/resources/application.yml
> +    address: dev@tdl.org
Let's update this and above to `helpdesk@library.tamu.edu`. It is a overlooked copy and paste from Vireo.

2022-06-21 00:19 UTC, wwelling commented on pom.xml
> +      <exclusions>
This exclusion workaround is corrected in latest release of weaver and can be removed.

2022-06-21 13:51 UTC, kaladay approved these changes

2022-06-21 15:50 UTC, merged